### ISSUE TITLE
How to include test name in report test column when test includes docstring

### ISSUE THREAD

**Issue by sarchule** [pytest-dev/pytest-html#200] opened 2019-04-09 21:02 UTC
When a pytest test method includes a docstring, then the report appears to use the docstring within the "test" column as the test id. If I remove the docstring, then the report uses the test method name. Is there a way to keep the docstring, but have the report still include the test method name within the "test" column? e.g., 
mytest.py::mytestclass::mytestmethodname::docstring....

Or if this is not possible, then to simply not include the docstring at all within the "test" column:
mytest.py::mytestclass::mytestmethodname

Thanks

**Comment by BeyondEvil** [comment] 2019-04-10 08:18
Hi @sarchule !

Could you provide us with some more detail? Python/pytest versions etc? Maybe an example snippet and report (screenshot)? I'm not able to reproduce it.

Cheers

**Comment by sarchule** [comment] 2019-04-11 19:09
Python: Python 3.7.0 (default, Aug 14 2018, 19:12:50) [MSC v.1900 32 bit (Intel)]
pytest related packages:
pytest                   4.3.1
pytest-cov               2.6.1
pytest-forked            1.0.2
pytest-html              1.20.0
pytest-logging           2015.11.4
pytest-metadata          1.8.0
pytest-ordering          0.6
pytest-pspec             0.0.3
pytest-rerunfailures     6.0
pytest-testdox           1.0.1
pytest-xdist             1.26.1

Sample pytest module (test_sample.py):
class TestClass(object):

    def test_one(self):
        """One line docstring here"""
        assert True

    def test_two(self):
        assert True

Test report output (Test col only) after "pytest --html=test_result.html test_sample.py":
![image](https://user-images.githubusercontent.com/34318189/55984010-b5981b00-5c59-11e9-88a3-3b486434b4fc.png)

Request is that I also want to see "test_one" in the report output (not just have it replaced with the doc string). In my case, I'm actually using a multi-line doc string to describe the test, but I don't want to duplicate the test_name within the doc string just to have it show up in the report.

**Comment by BeyondEvil** [comment] 2019-04-11 21:09
@sarchule  Awesome, thanks!

Initial testing with just...

pytest==4.4.0
pytest-html==1.20.0
pytest-metadata==1.8.0

...in the env shows that it works as expected. Gut feeling is that pytest-testdox is re-writing the node-id of the test.

**Comment by BeyondEvil** [comment] 2019-04-11 21:31
@sarchule

**Comment by BeyondEvil** [comment] 2019-04-11 21:32
@sarchule 

Ok, so I was wrong. It's actually pytest-pspec that is the offender. It re-writes the nodeid of the test, as can be seen here:

https://github.com/gowtham-sai/pytest-pspec/blob/master/pytest_pspec/plugin.py#L48

With that said, I say you should raise this issue with the pspec folks.

I'll close this issue, but feel free to re-open if you have a different point of view!

**Closed by BeyondEvil** 2019-04-11 21:32 UTC

**Comment by sarchule** [comment] 2019-04-11 21:40
Nice catch -- thanks for the quick response! I just confirmed your analysis and agree that the issue should be closed out.
