### ISSUE TITLE
[questions] using pytest_configure() generate report failed when pytest run in parent directory

### ISSUE THREAD

**Issue by chen97-y** [pytest-dev/pytest-html#302] opened 2020-06-02 15:47 UTC
I want to specify report name in conftest.py, and try pytest_configure(), it worked when i run pytest in directory script. However,when i run pytest in directory:"pytest_learning",it can't generate html report,can someone help?
Thanks in advance
My project structure:
pytest_learning:
|---- script/
|--------- conftest.py
|--------- test_learning.py
part code in conftest.py:
```
def pytest_configure(config):
    if not os.path.exists(log_path):
        os.mkdir(log_path)
    if not config.option.htmlpath:
        config.option.htmlpath = log_path + '\\' + time.strftime('%m-%d %H-%M', time.localtime()) + '.html'
```

**Comment by BeyondEvil** [comment] 2020-06-03 08:57
Could you create a small repo where this is reproducible please, @cy546342058 ?

**Comment by cy546342058** [comment] 2020-06-08 12:00
sorry,only now see the information.
repo attach the link below,very simple..
https://github.com/cy546342058/pytest_learning.git

**Comment by cy546342058** [comment] 2020-06-08 12:07
When I input the command 'pytest -sv' in directoery:"pytest",it can't generate html file.But when input 'pytest -sv script/', it can generate report.html
My python version is 2.7.13

**Comment by chtcs-vamsi** [comment] 2020-06-17 15:00
hi @chen97-y  can you tell me the significance of '-sv' in the command

**Comment by BeyondEvil** [comment] 2020-07-15 23:12
What version of the plugin are you using?

Since v2, we don't support python 2.7 anymore.

But I'll have a quick look to see if it's something simple.

**Comment by gnikonorov** [comment] 2020-11-09 03:32
I'll try and see if I can still reproduce this @chen97-y

**Comment by gnikonorov** [comment] 2020-11-09 04:49
Hi @chen97-y unfortunately I can't reproduce this with current python versions, and as @BeyondEvil mentioned we no longer support python 2.7.

In fact, when you try and install this plugin from head with python 2.7, the install fails as you can see below:
```
$ python --version
Python 2.7.17
$ pip install -e ~/pytest-html/
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Obtaining file:///home/gnikonorov/pytest-html
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
ERROR: Package u'pytest-html' requires a different Python: 2.7.17 not in '>=3.6'
$
```

My recommendation for you is to update your python to 3.6+. Here is some documentation from python's website you can reference: https://devguide.python.org/#status-of-python-branches. Python 2.7 has been sunsetted already. You can read more about this here: https://www.python.org/doc/sunset-python-2/

**Comment by gnikonorov** [comment] 2020-11-09 04:51
Closing this as per the above. @chen97-y please reopen this issue if it still occurs with a supported python version

**Closed by gnikonorov** 2020-11-09 04:51 UTC
Labels: bug, question
