### ISSUE TITLE
Feature request : Testsuite markup

### ISSUE THREAD

**Issue by Formartha** [pytest-dev/pytest-html#160] opened 2018-04-27 06:24 UTC
Hi,
I would love to have the ability to view suites in the tests I ran (meaning, pytest is scanning an entire directory with test-suites folders).

I would love to have the ability to cut down the report into test-suite listed view..

Can it be done?

in our company we are using the following structure:

- Prooduct_A;
   - test_suiteA1:
             __init__.py
             test_A1.py
             test_A2.py
    - test_suiteA2:
              __init__.py
              test_A12.py
              test_A22.py

- Product_B:
   - test_suiteB1:
             __init__.py
             test_B1.py
             test_B2.py
    - test_suiteB2:
              __init__.py
              test_B12.py
              test_B22.py

**Comment by davehunt** [comment] 2018-04-27 10:28
Thanks for the request. I believe this is a duplicate of #33.

**Closed by davehunt** 2018-04-27 10:28 UTC

**Comment by Formartha** [comment] 2018-04-27 10:30
well. It's not the same according to my opinion.
However I can see some points of similarity...

**Comment by davehunt** [comment] 2018-04-27 10:48
I think both users could be satified by a single solution. Please feel free to add your thoughts to the existing issue.
