### ISSUE TITLE
pytest_html_results_table_html hook is not passed any data

### ISSUE THREAD

**Issue by VegarS** [pytest-dev/pytest-html#667] opened 2023-05-08 14:43 UTC
I am testing the 4.0.0rc4 release and have had some issues porting code that modifies the captured log output. (I want to hide the setup output from the log, which I have achieved without problems in the 3.x.x releases)

The pytest_html_results_table_html hook is always passed an empty data object, so it is impossible to _modify_ the output. Printing data.html argument inside the hook always yields the same value: `{'html': []}`

Additionally, adding elements to data.html has no effect unless I delete something from data first (which sets data._replace_log = True).

How is this intended to work?

**Comment by BeyondEvil** [comment] 2023-05-08 16:23
Interesting.

Mind telling me more about your use-case and giving me a concrete example of what you're doing?

**Comment by VegarS** [comment] 2023-05-08 18:42
This is the full code that works in 3.1.1. It replaces the last html element in the data argument  (the output log) with a more elaborate html code with checkboxes to show/hide setup and call logs separately.

```@pytest.hookimpl(optionalhook=True)
def pytest_html_results_table_html(report, data):
    """ Split log into setup and call """
    if len(data) and len(data[-1]):
        # Find start-index for setup and call logs
        setup_idx = [i for i,elem in enumerate(data[-1]) if type(elem) == str and 'Captured stdout setup' in elem]
        call_idx = [i for i,elem in enumerate(data[-1]) if type(elem) == str and 'Captured stdout call' in elem]
        if not len(setup_idx):
            return
        setup_idx = setup_idx[0]
        other_data = data[-1][:setup_idx]
        new_data = html.div()
        if len(other_data):
            new_data.append(html.div(other_data, class_='log'))

        # Retrieve setup log
        setup_txt = data[-1][setup_idx+2]
        last_processed_idx = setup_idx+2
        # Create checkbox to show/hide setup log
        node_id = uuid.uuid4() # random id
        new_data.append(html.input(id=node_id, class_='toggle', type='checkbox'))
        new_data.append(html.label('Show setup output', for_=node_id, class_='lbl-toggle'))
        new_data.append(html.div(setup_txt, class_='log collapsible-content'))
        if len(call_idx):
            call_idx = call_idx[0]
            call_txt = data[-1][call_idx+2]
            last_processed_idx = call_idx+2
            # Checkbox for call log
            node_id = uuid.uuid4() # random id
            new_data.append(html.input(id=node_id, class_='toggle', type='checkbox', checked='checked'))
            new_data.append(html.label('Show test output', for_=node_id, class_='lbl-toggle'))
            new_data.append(html.div(call_txt, class_='log collapsible-content'))
        elif not len(other_data):
            new_data[0].attr.checked = 'checked' # show setup if no call log and no other data
        if last_processed_idx+1 < len(data[-1]):
            # Keep any other data that is appended
            new_data.append(html.div(data[-1][last_processed_idx+1:], class_='log'))
        data[-1] = new_data
```

The result looks like this:
![image](https://user-images.githubusercontent.com/1231463/236905536-342012b3-35f8-4a8e-ba93-dfa79a3a7696.png)

@BeyondEvil

**Comment by BeyondEvil** [comment] 2023-05-08 18:43
Ooh... that's pretty nice actually. 🤔

**Comment by BeyondEvil** [comment] 2023-05-08 18:44
Does it not work in 3.2.0?

**Comment by BeyondEvil** [comment] 2023-05-08 19:49
Damn, this is a bit tricky after the refactor...

I'm wondering if the easiest way is to wrap all the headers (`Captured stdout call`, `Captured stdout setup`, etc) in a DOM class/id.

**Comment by VegarS** [comment] 2023-05-08 20:52
> Does it not work in 3.2.0?

I believe it works in 3.2.0 too, but we are having issues with UnicodeEncodeErrors similar to #559 which keeps us at 3.1.1. The fix for the errors is to upgrade to 4.0.0, but then we hit this issue.

**Comment by BeyondEvil** [comment] 2023-05-09 07:16
Ok.

I won't be able to fix this in a non-breaking way unfortunately. At least not in a non-brittle way.

What I can do is to make the `data` passed to the hook more structured.

In legacy, `data` contains two things:

- "Additional HTML" which is basically all `extras.HTML`
- Logs

So I'll make sure that the `data` object now contains those attributes.

- `additional_html` will be a list (just like before)
- the logs will be a dictionary where the headers ("Captured stdout setup" etc.) will be the keys.

Then in the JS, each header will be wrapped in a div with either some class or id that makes sense.

Thoughts @VegarS ?

**Comment by VegarS** [comment] 2023-05-09 07:26
Hmm.. interesting. Will this allow me to achieve a similar setup as in legacy, i.e. add html for checkboxes in the hook?

**Comment by BeyondEvil** [comment] 2023-05-09 07:35
I'm not sure, haha.

But I _think_ you'll be able to add your logic to the `additional_html` list and have it work. Basically attach the checkboxes logic to the class/id of the headers/logs.


Another option is to basically relinquish all control of the log to you (the user). That way you can provide whatever HTML you want, and the frontend will render it.

Not really a fan of that type of omnipotent user-power, but might go that way.

If you're up for it, we can investigate the first option and see if we can solve it?

**Comment by VegarS** [comment] 2023-05-09 07:42
Yes, lets give the first proposal a chance. Let me know what and when to test :)

**Comment by BeyondEvil** [comment] 2023-05-09 07:47
Will do!

Not sure what TZ your in. My day just started and I have to focus on my day job. But hopefully I'll have something you can test tomorrow my TZ (Stockholm).

**Comment by VegarS** [comment] 2023-05-09 08:04
Excellent! I am in the same timezone (Oslo) and can test as part of my day job or later in the evening.

**Comment by VegarS** [comment] 2023-05-09 10:40
Managed to work around it by retrieving the log data from report.sections and manually setting data._replace_log = True (which I believe should not be necessary and is a bug):

![bilde](https://github.com/pytest-dev/pytest-html/assets/1231463/9f022926-75a3-4bb4-8af0-b4a1975793e1)

Code:
```@pytest.hookimpl(optionalhook=True)
def pytest_html_results_table_html(report, data):
    if report.when in ('call', 'teardown'):
        setup_text = None
        call_text = None
        other_text = ''
        for title,text in report.sections:
            if 'Captured stdout setup' in title:
                setup_text = text
            elif 'Captured stdout call' in title:
                call_text = text
            else:
                other_text += text
        if setup_text is None or len(setup_text) == 0:
            return #??

        html = []
        node_id = uuid.uuid4() # random id
        html.append(f'<input id="{node_id}" class="toggle" type="checkbox">') # Setup checkbox
        html.append(f'<label for="{node_id}" class="lbl-toggle">Show setup output</label>') # Label
        html.append(f'<div class="log collapsible-content">{setup_text}</div>') # Setup log
        if call_text is not None and len(call_text):
            node_id = uuid.uuid4() # random id
            html.append(f'<input id="{node_id}" class="toggle" type="checkbox" checked>') # Call checkbox
            html.append(f'<label for="{node_id}" class="lbl-toggle">Show test output</label>') # Label
            html.append(f'<div class="log collapsible-content">{call_text}</div>') # Call log
        elif not len(other_text):
            # show setup if no call log and no other data
            html[0].replace('<input ', '<input checked ')

        if len(other_text):
            html.append('<div class="log">'+other_text+'</div>')

        data._replace_log = True
        data.append('<div>'+''.join(html)+'</div>')
```

**Comment by BeyondEvil** [comment] 2023-05-09 10:52
I tried reproducing the replace _log thing, but failed.

Would you mind providing a minimal repro case?

Basically what you have above, but also test and setup to help me repro?


I still think creating a proper structure of the logs is a good thing.

**Comment by BeyondEvil** [comment] 2023-05-09 11:08
Also, that code "pytest_html_results_table_html" is so much cleaner. 👍

**Comment by BeyondEvil** [comment] 2023-05-09 11:11
Ah, I think I know what's happening.

Try replacing `data._replace_log = True` with `del data[:]`

**Comment by VegarS** [comment] 2023-05-09 11:17
Yes, that is correct. del data[:] has the same effect.

**Comment by VegarS** [comment] 2023-05-10 09:24
The suggestion in #669 seems to be working for my use case here. My added HTML is now inside the `<div class="log">` element, but that is not really an issue for me. It means I can drop the surrounding `<div>` element from my code.

> So in the new version, instead of `del data[:]` you could do:
> `data = ['<div>'+''.join(html)+'</div>']`

Reassigning data as you suggest does not work, but I can do this: `data[:] = [''.join(html)]`

One issue that this approach does not solve: In legacy I could change the text in the test name column from the `pytest_html_results_table_html` hook (I typically strip full file paths), but I have worked around this by changing the value of `report.nodeid` in `pytest_runtest_makereport` instead. Is that an "acceptable" solution or could I break things when modifying the nodeid property?

Another solution is to add a new column for the simplified test name using `pytest_html_results_table_header` and `pytest_html_results_table_row`, but I cannot see any way to delete the original test name column like you could in legacy?

Third option is to use the above approach and add CSS to hide the original test name column, but is there a suitable hook to inject the CSS (I would prefer not to add a new file for a single line of CSS)?

**Comment by BeyondEvil** [comment] 2023-05-10 10:38
> The suggestion in #669 seems to be working for my use case here. My added HTML is now inside the `<div class="log">` element, but that is not really an issue for me. It means I can drop the surrounding `<div>` element from my code.
> 
> > So in the new version, instead of `del data[:]` you could do:
> > `data = ['<div>'+''.join(html)+'</div>']`
> 
> Reassigning data as you suggest does not work, but I can do this: `data[:] = [''.join(html)]`

Mind sharing in what way reassigning doesn't work? Nothing happens or there's an error?

> One issue that this approach does not solve: In legacy I could change the text in the test name column from the `pytest_html_results_table_html` hook (I typically strip full file paths), but I have worked around this by changing the value of `report.nodeid` in `pytest_runtest_makereport` instead. Is that an "acceptable" solution or could I break things when modifying the nodeid property?

How did you change the test name in legacy? I don't see that logic in your previous examples. Did you use the `report` or `data` object to do that?

I would not modify `nodeid` (or any attributes on the `report` object) directly. This may have unintended consequences and will for sure lead to hard to debug issues now or in the future.

> Another solution is to add a new column for the simplified test name using `pytest_html_results_table_header` and `pytest_html_results_table_row`, but I cannot see any way to delete the original test name column like you could in legacy?

Currently, the new version doesn't support deleting default columns (apart from `Links`). We have on our roadmap to support this.

> Third option is to use the above approach and add CSS to hide the original test name column, but is there a suitable hook to inject the CSS (I would prefer not to add a new file for a single line of CSS)?

No hooks unfortunately. Regardless, that sounds like more of a hack than a solution.

I wonder if there's a fourth option. Maybe we expose the `ReportData` object in some way for these types of modifications.

But first, I'd really like to understand how you did this in legacy.

**Comment by VegarS** [comment] 2023-05-10 11:17
My mistake, I changed the test name in `pytest_html_results_table_row` in legacy, not `_table_html`, see code below. There are two challenges here:

- The `cells` argument does not contain data that goes into the html table (small issue, I can get test name from report.nodeid), and
- it is not possible to overwrite existing column values, only insert new columns? (dealbreaker)

```
@pytest.hookimpl(optionalhook=True)
def pytest_html_results_table_row(report, cells):
    #cells[0].style = html.Style(white_space='nowrap')
    # Clean up test name and arguments
    test_col = cells[1]
    test_text = test_col[0]
    test_func = os.path.basename(test_text.split('[')[0])
    test_args = test_text.split('[',1)[-1]
    other = test_args.split(']',1)
    test_args = other[0]
    other_info = other[1:]
    test_col[0] = '{}[{}]{}'.format(test_func, os.path.basename(test_args), ''.join(other_info))
```

**Comment by BeyondEvil** [comment] 2023-05-10 11:23
I'll investigate the first bullet. That might be an easy fix.

The other one is on our radar and we're planning on implementing a solution for that. However, it's unlikely it will be part of 4.0.0 which has dragged on long enough and needs to come out.

I'll see (tomorrow, no time today) if there's a workaround.

But what you're trying to do is change the test name, correct? Or are there other columns you want to modify?

**Comment by VegarS** [comment] 2023-05-10 12:44
Sounds good and that is correct, I am only trying to change the test name.

As long as I am able to use the current workarounds a release of 4.0.0 is very welcome from our side.

**Comment by BeyondEvil** [comment] 2023-05-10 13:41
Cool.

I'll do some work tomorrow and hopefully release 4.0.0rc5 before EOW for you to test.

If all goes well, I'll release 4.0.0 next week (and brace for impact 😂 )

**Comment by BeyondEvil** [comment] 2023-05-10 20:28
Unfortunately, bullet one is not an easy fix either (w.r.t. to the row hook).

So a solution for that will come later.

Would you mind opening new issues for those as this one will be closed once I merge the PR.

Thanks for all your input, it's been invaluable! 🙏

**Comment by VegarS** [comment] 2023-05-11 07:08
#674 and #675 created. Thanks for all the help so far.

**Comment by VegarS** [comment] 2023-05-12 10:59
I am having some issues with the pull request. I install it with pip like this: `py -3.9 -m pip install git+https://github.com/pytest-dev/pytest-html.git@refs/pull/669/merge`

At random points during a (relatively) long-running test suite, I get a permission error on the resulting HTML file. I do not have this issue with the current master branch (g15356c8). Sometimes it occurs at 1 % test progress, sometimes closer to 50 % or 90 %.

All my pytest-html hooks are disabled.

Am I installing the pull request code incorrectly or is there a new bug being introduced?

How do we debug this further?

Full error:
```
tests\10_xx\test_yyy.py sss
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "C:\Users\vegarst\AppData\Roaming\Python\Python39\site-packages\_pytest\main.py", line 270, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "C:\Users\vegarst\AppData\Roaming\Python\Python39\site-packages\_pytest\main.py", line 324, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "C:\Users\vegarst\AppData\Roaming\Python\Python39\site-packages\pluggy\_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "C:\Users\vegarst\AppData\Roaming\Python\Python39\site-packages\pluggy\_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "C:\Users\vegarst\AppData\Roaming\Python\Python39\site-packages\pluggy\_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "C:\Users\vegarst\AppData\Roaming\Python\Python39\site-packages\pluggy\_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "C:\Users\vegarst\AppData\Roaming\Python\Python39\site-packages\pluggy\_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "C:\Users\vegarst\AppData\Roaming\Python\Python39\site-packages\_pytest\main.py", line 349, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "C:\Users\vegarst\AppData\Roaming\Python\Python39\site-packages\pluggy\_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "C:\Users\vegarst\AppData\Roaming\Python\Python39\site-packages\pluggy\_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "C:\Users\vegarst\AppData\Roaming\Python\Python39\site-packages\pluggy\_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "C:\Users\vegarst\AppData\Roaming\Python\Python39\site-packages\pluggy\_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "C:\Users\vegarst\AppData\Roaming\Python\Python39\site-packages\pluggy\_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "C:\Users\vegarst\AppData\Roaming\Python\Python39\site-packages\_pytest\runner.py", line 112, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "C:\Users\vegarst\AppData\Roaming\Python\Python39\site-packages\_pytest\runner.py", line 125, in runtestprotocol
INTERNALERROR>     rep = call_and_report(item, "setup", log)
INTERNALERROR>   File "C:\Users\vegarst\AppData\Roaming\Python\Python39\site-packages\_pytest\runner.py", line 224, in call_and_report
INTERNALERROR>     hook.pytest_runtest_logreport(report=report)
INTERNALERROR>   File "C:\Users\vegarst\AppData\Roaming\Python\Python39\site-packages\pluggy\_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "C:\Users\vegarst\AppData\Roaming\Python\Python39\site-packages\pluggy\_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "C:\Users\vegarst\AppData\Roaming\Python\Python39\site-packages\pluggy\_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "C:\Users\vegarst\AppData\Roaming\Python\Python39\site-packages\pluggy\_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "C:\Users\vegarst\AppData\Roaming\Python\Python39\site-packages\pluggy\_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "C:\Users\vegarst\AppData\Roaming\Python\Python39\site-packages\pytest_html\basereport.py", line 224, in pytest_runtest_logreport
INTERNALERROR>     self._generate_report()
INTERNALERROR>   File "C:\Users\vegarst\AppData\Roaming\Python\Python39\site-packages\pytest_html\selfcontained_report.py", line 39, in _generate_report
INTERNALERROR>     super()._generate_report(self_contained=True)
INTERNALERROR>   File "C:\Users\vegarst\AppData\Roaming\Python\Python39\site-packages\pytest_html\basereport.py", line 68, in _generate_report
INTERNALERROR>     self._write_report(rendered_report)
INTERNALERROR>   File "C:\Users\vegarst\AppData\Roaming\Python\Python39\site-packages\pytest_html\basereport.py", line 150, in _write_report
INTERNALERROR>     with self._report_path.open("w", encoding="utf-8") as f:
INTERNALERROR>   File "C:\Program Files\Python39\lib\pathlib.py", line 1252, in open
INTERNALERROR>     return io.open(self, mode, buffering, encoding, errors, newline,
INTERNALERROR>   File "C:\Program Files\Python39\lib\pathlib.py", line 1120, in _opener
INTERNALERROR>     return self._accessor.open(self, flags, mode)
INTERNALERROR> PermissionError: [Errno 13] Permission denied: 'Resultater.html'
```

**Comment by BeyondEvil** [comment] 2023-05-12 11:44
Do you by any chance use pytest-xdist or an async framework or such?

My initial thought is that it might be a race condition.

It shouldn’t be related to it being a PR branch, but can you try (in the pytest-html repo):

```
rm -rf node_modules
npm ci
npm run build
```

You’ll need node 16.x for this.

**Comment by VegarS** [comment] 2023-05-12 11:52
Nothing async as far as I know. Plugins reported by pytest:
`plugins: anyio-3.6.2, cov-4.0.0, html-4.0.0rc5.dev14+ga5f4329, metadata-2.0.4`

**Comment by VegarS** [comment] 2023-05-12 12:31
I have node 18.16.0. Tried a couple of new approaches to check out the pull request because I don't fully trust my git-fu:

### Approach 1
Check out master with plain git client and fetch the pull request as a branch:
- checked out the pull request with `git fetch origin pull/669/head:pull669`
- switched to the pull669 branch
- `npm ci`and `npm run build` (deleted node_modules first)
- `pip install .` in the repository folder (which builds a wheel in a clean temp dir)

I am not able to reproduce the error this time, not even with my own hooks reintroduced.

### Approach 2
Using github desktop I cloned pytest-dev/pytest-html, selected the pull request from the branches menu and then merged master into the pull request branch to ensure everything is up to date. Installed with pip and everything seems to be working.

I have no idea what caused the above error, but it seems to be a non-issue when checked out properly.

**Comment by BeyondEvil** [comment] 2023-05-12 12:37
So happy to hear that 😅

I’ll release RC5 during this weekend so you can run a final set of tests against a real release. Just to be sure. ☺️👍

**Closed** 2023-05-13 18:36 UTC

**Comment by VegarS** [comment] 2023-05-26 09:50
No RC5 release yet, but I can confirm that current master works as expected. Is there any timeline for RC5 or official release of 4.0.0?
