### ISSUE TITLE
pytest-html isn’t escaping HTML special characters in logs

### ISSUE THREAD

**Issue by andrewshadura** [pytest-dev/pytest-html#100] opened 2017-01-15 12:37 UTC
I’m seeing things like:

    auth.py                    518 DEBUG    Auth User is now <authuser('id:1[default] auth:true')>

in the HTML sources of the generated reports. That’s apparently due to a [missing escape call](/pytest-dev/pytest-html/commit/f84482bc6a28a547602b5f4e07ffc9044ee427b0#commitcomment-20481987).

**Comment by davehunt** [comment] 2017-01-16 10:45
I'm not sure I understand this issue. Could you provide details of the expected output? Also, if you've identified the cause, perhaps you could provide a pull request with a fix and a test? Thanks!

**Comment by andrewshadura** [comment] 2017-01-16 11:20
You’re not escaping `<`, `>` and other HTML special characters in the test output. The example above shows that very clear, `<` and `>` should have been replaced by `&lt;` and `&gt;`.

**Comment by andrewshadura** [comment] 2017-01-16 11:20
That happens only when ANSI parsing is disabled, which it is by default.

**Comment by braunman** [comment] 2017-02-09 07:48
Caught same problems, it will be fixed?

**Comment by davehunt** [comment] 2017-02-09 10:23
> Caught same problems, it will be fixed?

I haven't had time to look into this. If you have a fix, please submit a pull request with a test and I'll happily review it.

**Comment by davehunt** [comment] 2017-02-23 19:52
This should be fixed by #102. I have a few other items to look into before a new release, but it should be soon! Thanks for the report.

**Comment by davehunt** [comment] 2017-02-24 12:55
I'll release 1.14.0 soon (maybe today) with this fix.

**Closed** 2017-02-24 12:55 UTC
