### ISSUE TITLE
Encoding issue,  return codecs.charmap_encode(input,errors,encoding_table) INTERNALERROR> UnicodeEncodeError: 'charmap' codec can't encode character '\ufffd' in position 24465: character maps to <undefined>

### ISSUE THREAD

**Issue by chennareddy08** [pytest-dev/pytest-html#227] opened 2019-08-08 15:59 UTC
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\_pytest\main.py", line 185, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\_pytest\main.py", line 225, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pluggy\hooks.py", line 284, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pluggy\manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pluggy\manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\_pytest\main.py", line 246, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pluggy\hooks.py", line 284, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pluggy\manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pluggy\manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\_pytest\runner.py", line 76, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\_pytest\runner.py", line 91, in runtestprotocol
INTERNALERROR>     reports.append(call_and_report(item, "call", log))
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\_pytest\runner.py", line 175, in call_and_report
INTERNALERROR>     hook.pytest_runtest_logreport(report=report)
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pluggy\hooks.py", line 284, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pluggy\manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pluggy\manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\helpers\pycharm\teamcity\pytest_plugin.py", line 329, in pytest_runtest_logreport
INTERNALERROR>     self.report_test_failure(test_id, report)
INTERNALERROR>   File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\helpers\pycharm\teamcity\pytest_plugin.py", line 255, in report_test_failure
INTERNALERROR>     self.report_test_output(report, test_id)
INTERNALERROR>   File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\helpers\pycharm\teamcity\pytest_plugin.py", line 236, in report_test_output
INTERNALERROR>     dump_test_stdout(self.teamcity, test_id, test_id, data)
INTERNALERROR>   File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\helpers\pycharm\teamcity\common.py", line 73, in dump_test_stdout
INTERNALERROR>     messages.testStdOut(test_id, chunk, flowId=flow_id)
INTERNALERROR>   File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\helpers\pycharm\teamcity\messages.py", line 167, in testStdOut
INTERNALERROR>     self.message('testStdOut', name=testName, out=out, flowId=flowId)
INTERNALERROR>   File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\helpers\pycharm\_jb_runner_tools.py", line 113, in message
INTERNALERROR>     _old_service_messages.message(self, messageName, **properties)
INTERNALERROR>   File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\helpers\pycharm\teamcity\messages.py", line 81, in message
INTERNALERROR>     self.output.write(self.encode(message))
INTERNALERROR>   File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\helpers\pycharm\teamcity\messages.py", line 48, in encode
INTERNALERROR>     value = value.encode(self.encoding)
INTERNALERROR>   File "C:\Users\cbiradar\AppData\Local\Programs\Python\Python37-32\lib\encodings\cp1252.py", line 12, in encode
INTERNALERROR>     return codecs.charmap_encode(input,errors,encoding_table)
INTERNALERROR> UnicodeEncodeError: 'charmap' codec can't encode character '\ufffd' in position 24465: character maps to <undefined>

**Comment by BeyondEvil** [comment] 2019-08-08 17:16
What version of pytest-html are you using?
What version python are you using?

Does this happen with other versions?

Can you reproduce this outside of PyCharm?

Could you provide a minimal reproducible case?

**Comment by chennareddy08** [comment] 2019-10-27 23:03
What version of pytest-html are you using--2.0.0
What version python are you using?--3.7

Does this happen with other versions?-yes 

Can you reproduce this outside of PyCharm?-yes in eclipse with pydev 
also with terminal or cmd

Could you provide a minimal reproducible case?
when json file is large like
gray log api response giving more logs ,that time this issue will come

**Comment by BeyondEvil** [comment] 2019-11-03 04:03
Thanks for that @chennareddy08 !

I'm currently on a business trip, but as soon as I'm back I'll look into this. Please ping me in two weeks if you haven't heard anything by then. 🙏

**Comment by sachinrathi007** [comment] 2020-06-15 12:25
instead of file = open(filename, "a")
use below-
file = open(filename, "a",encoding="utf-8")

**Comment by gnikonorov** [comment] 2020-11-03 02:42
I'll take a look at this one @chennareddy08

**Comment by gnikonorov** [comment] 2020-11-03 05:36
Does this still happen for you @chennareddy08 ?

Looking at the stack trace it looks like this comes from `"C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\helpers\pycharm\teamcity\messages.py`, which is unrelated to this plugin. I also don't see `pytest-html` in the stack trace.

Can you provide a minimal reproducer? It would help in tracking down the issue.

**Comment by gnikonorov** [comment] 2020-11-07 02:56
Hi @chennareddy08. I'm going to close this issue since (a) it is very old and (b) requires more information to properly debug.

If this is still occurring for you, please reopen this issue and I can take a look.

**Closed by gnikonorov** 2020-11-07 02:56 UTC
Labels: bug, needs more info
