### ISSUE TITLE
Screenshot images are broken

### ISSUE THREAD

**Issue by kottenator** [pytest-dev/pytest-html#78] opened 2016-09-21 20:54 UTC
Hi!

Your plugin is great! But since version `1.10.0` I get all the screenshot images broken:

![screenshot](https://cloud.githubusercontent.com/assets/371674/18728606/f223d91e-801b-11e6-9af6-cfcd7c6f5f46.png)

**Comment by davehunt** [comment] 2016-09-22 10:56
Could be a duplicate (or the real issue behind) https://github.com/pytest-dev/pytest-selenium/issues/79. Are you able to provide me with the damaged image for inspection, or perhaps steps to reproduce?

**Comment by davehunt** [comment] 2016-09-23 10:06
I can replicate this with python 3.5.2 (but not python 2.7.12). It's related to creating the assets file, so a temporary workaround would be to add `--self-contained-html` to the command line.

**Comment by davehunt** [comment] 2016-09-23 13:19
@kottenator could you try installing the v1.10.1 release candidate and let me know if the issue is fixed? `pip install --upgrade --pre pytest-html`

**Comment by davehunt** [comment] 2016-09-23 21:36
I got confirmation from someone else, released 1.10.1, so closing this. Please reopen if you still see issues: https://pypi.python.org/pypi/pytest-html/1.10.1

**Closed by davehunt** 2016-09-23 21:36 UTC
Labels: bug

**Comment by kottenator** [comment] 2016-09-24 20:46
Sorry, I was extremely busy. Yes, I can see that it works now. Thanks a lot! ;)
