### ISSUE TITLE
Pytest-html 3.0.0 does not capture logs

### ISSUE THREAD

**Issue by buster3** [pytest-dev/pytest-html#378] opened 2020-11-23 15:12 UTC
Since pytest-html==3.0.0 I get "No log output captured." in the html output. Everything works fine for pytest-html==2.1.1. Is this an intended change? How do I re-enable the log capture?

I generate log messages using 

```python
  import logging

    def test_pass():
        logging.info('info pass test')
```

**Comment by gnikonorov** [comment] 2020-11-23 15:24
Hi @buster3 I'm fairly certain this works as designed. I'll confirm when I have time today in the evening and explain what changed. 

In the meantime I think you need to pass --capture=no to disable capturing. See [this link](https://docs.pytest.org/en/latest/capture.html) for more info.

**Comment by gnikonorov** [comment] 2020-11-24 04:58
@buster3 - the change is intentional, as we were incorrectly including captured log information.

As per the [logger.setLevel() documentation](https://docs.python.org/3/library/logging.html#logging.Logger.setLevel) the root logger is created with a default level of `WARNING`. This means that a call to `logging.info` should be ignored by the logger and therefore **not** appear in captured logs. In v2.1.1 we were including it, however.


To work around this, all we need to do is use a logger with a level set to a value less than or equal to `logging.INFO`. The following test file would include the logger output since `logging.INFO` is the logging level for `.info()`, for example:
```
import logging

my_logger = logging.getLogger()
my_logger.setLevel(logging.INFO)

def test_logging():
    my_logger.info('the following log line will be captured')
```

**Comment by gnikonorov** [comment] 2020-11-24 04:58
As per the above comment, I am closing this issue. @buster3 if my answer is unsatisfactory, please feel free to reopen this issue.

**Comment by buster3** [comment] 2020-11-24 08:06
@gnikonorov Thanks for your explanation! Still, I expect to get logs if I set a global `log_level = INFO` in my pytest.ini file.

Pytest documentation writes (https://docs.pytest.org/en/stable/logging.html):
```Log levels are no longer changed unless explicitly requested by the log_level configuration or --log-level command-line options. This allows users to configure logger objects themselves. Setting log_level will set the level that is captured globally so if a specific test requires a lower level than this, use the caplog.set_level() functionality otherwise that test will be prone to failure.```

**Comment by buster3** [comment] 2020-11-24 08:14
> @buster3 - the change is intentional, as we were incorrectly including captured log information.
> 
> As per the [logger.setLevel() documentation](https://docs.python.org/3/library/logging.html#logging.Logger.setLevel) the root logger is created with a default level of `WARNING`. This means that a call to `logging.info` should be ignored by the logger and therefore **not** appear in captured logs. In v2.1.1 we were including it, however.
> 
> To work around this, all we need to do is use a logger with a level set to a value less than or equal to `logging.INFO`. The following test file would include the logger output since `logging.INFO` is the logging level for `.info()`, for example:
> 
> ```
> import logging
> 
> my_logger = logging.getLogger()
> my_logger.setLevel(logging.INFO)
> 
> def test_logging():
>     my_logger.info('the following log line will be captured')
> ```

I also do not expect that changing the level of `my_logger` changes the behavior. As  [documented](https://docs.python.org/3/library/logging.html#logging.Logger.setLevel), only the root logger is created with level WARNING. `my_logger` should have default level NOTSET?

```When a logger is created, the level is set to NOTSET (which causes all messages to be processed when the logger is the root logger, or delegation to the parent when the logger is a non-root logger). Note that the root logger is created with level WARNING.```

**Comment by gnikonorov** [comment] 2020-11-24 14:15
I am able to capture logging from your reproducer with the following @buster3.

pytest.ini file:
```
[pytest]
log_level = INFO
```

test file:
```
$ cat issue_378_example.py
import logging

def test_pass():
    logging.info('info pass test')
$
```

command line run: `python3 -m pytest --html=issue_378.html issue_378_example.py`

relevant `pip3 list` output:
```
pytest (6.1.2)
pytest-html (3.0.0)
```

When I run the above I get:
![Screen Shot 2020-11-24 at 9 11 08 AM](https://user-images.githubusercontent.com/13026015/100105125-01023b80-2e35-11eb-9ba2-443808ec6914.png)

It sounds like it could be an environment issue then. Is there something different in your environment?

**Comment by buster3** [comment] 2020-11-25 08:26
Thanks for the feedback. I had a closer look on my environment. Actually we have a configuration similar to
```
[pytest]
addopts = -s
log_level = INFO
```

The `-s` seems to make the difference for pytest-html 2.1.1 and 3.0.0. Actually, I cannot say why we use this flag. Everything else is identical to your setup.

Sorry about the missing information and thanks for your help.

**Comment by gnikonorov** [comment] 2020-11-25 14:04
> The `-s` seems to make the difference for pytest-html 2.1.1 and 3.0.0. Actually, I cannot say why we use this flag. Everything else is identical to your setup.

We used to not respect -s. The change responsible for having this plugin take it into account was introduced in [this or](https://github.com/pytest-dev/pytest-html/pull/353) and made it into 3.0.0 which is why you noticed this on plugin upgrade.

> Sorry about the missing information and thanks for your help.

No worries @buster3! If you don't have further questions can you please resolve this issue

**Comment by gnikonorov** [comment] 2020-11-27 05:03
Closing this since it seems like your question was resolved. If you wanted to discuss this some more @buster3 please reopen this issue and @ mention me

**Closed by gnikonorov** 2020-11-27 05:03 UTC
Labels: question
