### ISSUE TITLE
Teardown log not shown in html

### ISSUE THREAD

**Issue by PhilippSelenium** [pytest-dev/pytest-html#145] opened 2018-02-08 13:12 UTC
The teardown log is not shown in the html despite being shown on the cmd line.

**Comment by davehunt** [comment] 2018-02-09 09:33
Please provide more details, as this feature is working fine for me. If you can reproduce with a simple test case, that would be ideal. Thanks!

**Comment by davehunt** [comment] 2018-02-12 12:10
Thank you, your additional information demonstrated that this in fact is fixture related setup/teardown. This is a duplicate of https://github.com/pytest-dev/pytest-html/issues/131 and I'd be happy to review any patches that add this functionality.

**Closed by davehunt** 2018-02-12 12:10 UTC
