### ISSUE TITLE
pytest suite split in the report

### ISSUE THREAD

**Issue by Formartha** [pytest-dev/pytest-html#147] opened 2018-02-12 06:07 UTC
One of the things I'm missing in the report is the ability to split the files into "suites".
Suite is a folder which holds 1 or more tests.

Each iteration, pytest is going and grabbing the specific suites and executes it.
in the HTML report, we can see all the tests, but it's not grouped in that way..

So for example, I have around 600 e2e tests and it will be easier to see the report with one more cut.

Thanks,
Mor

**Comment by davehunt** [comment] 2018-02-12 11:36
This sounds like a duplicate of #33

**Closed by davehunt** 2018-02-12 11:36 UTC

**Comment by Formartha** [comment] 2018-02-12 18:49
@davehunt  - No eta for it? :(

**Comment by davehunt** [comment] 2018-02-12 19:04
@Formartha sorry, I'm not aware of anyone working on it. I'm happy to review/merge a patch, but I don't have time to work on enhancements for the plugin myself at this time.
